#!/bin/bash

echo "TRON MetaMask Snap v1.0.3 - Ready to Publish!"
echo "=============================================="
echo ""
echo "New features in v1.0.3:"
echo "- TRX staking for energy/bandwidth"
echo "- Voting for Super Representatives"  
echo "- Withdrawal for unstaked TRX"
echo "- Fixed manifest shasum issue"
echo ""
echo "Files ready:"
echo "- dist/bundle.js (35.6 KiB)"
echo "- snap.manifest.json (shasum: cJksvj4m3l1GbEnGbyX6A7HZAEVVk5X9AfFvkUxzo+c=)"
echo "- package.json (v1.0.3)"
echo ""
echo "To publish:"
echo "1. Run: npm login"
echo "2. Enter your npm credentials"
echo "3. Run: npm publish"
echo ""
echo "Or if you have an npm token:"
echo "npm set //registry.npmjs.org/:_authToken YOUR_TOKEN"
echo "npm publish"