#!/bin/bash

echo "Push to GitHub with Authentication"
echo "=================================="
echo ""
echo "Since you're getting a 403 error, use one of these methods:"
echo ""
echo "Method 1: Using GitHub Personal Access Token"
echo "git push https://DERK333:YOUR_GITHUB_TOKEN@github.com/DERK333/tron-metamask-snap.git main"
echo ""
echo "Method 2: Set remote URL with token"
echo "git remote set-url origin https://DERK333:YOUR_GITHUB_TOKEN@github.com/DERK333/tron-metamask-snap.git"
echo "git push origin main"
echo ""
echo "To get a GitHub token:"
echo "1. Go to GitHub Settings > Developer settings > Personal access tokens"
echo "2. Generate a new token with 'repo' permissions"
echo "3. Replace YOUR_GITHUB_TOKEN with your actual token"
echo ""
echo "Note: Your changes are already committed locally,"
echo "you just need to push them to GitHub."